# Generated by Django 3.0.6 on 2020-05-29 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(0, 'плохо'), (1, 'ниже среднего'), (2, 'средне'), (3, 'выше среднего'), (4, 'хорошо'), (5, 'отчично')])),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='account.Citizen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='organizations.Organization')),
            ],
        ),
    ]
