# Generated by Django 3.0.6 on 2020-05-29 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('appeals', '0001_initial'),
        ('account', '0002_organizationrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_rating', to='appeals.Appeal')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_rating', to='account.Citizen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_grades', to='organizations.Organization')),
            ],
        ),
    ]
