# Generated by Django 3.0.6 on 2020-05-30 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_appealrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='external_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='tg_role',
            field=models.SmallIntegerField(choices=[(0, 'Житель'), (1, 'Старщий по дому'), (2, 'Сотрудник УК/ТСЖ')], default=0),
        ),
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='external_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tg_role',
            field=models.SmallIntegerField(choices=[(0, 'Житель'), (1, 'Старщий по дому'), (2, 'Сотрудник УК/ТСЖ')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
