# Generated by Django 3.0.6 on 2020-05-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200530_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
