# Generated by Django 3.0.6 on 2020-05-31 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
        ('account', '0005_auto_20200530_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='appeal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='appeals.Appeal'),
        ),
    ]
